name: DBT Pull Request
on:
  push:
    branches:
      - main

jobs:
   auto-pull-request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: extract git commit data
      uses: rlespinasse/git-commit-data-action@v1.x
    
    - name: Update author information
      run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR

    # - name: Set up Python
    #   uses: actions/setup-python@v2
    #   with:
    #     python-version: 3.9

    # - name: Install dependencies
    #   run: 
    #     pip install dbt-snowflake
    # - name: Run DBT
    #   run: dbt run

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
         token: ${{ secrets.GITHUB_TOKEN }}
         branch: "local"
         base: main
         title: "Pull request DBT"
         committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
         author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
         body: Automated Pull request
         delete-branch: false
    
    - name: Approve Pull Request
      uses: juliangruber/approve-pull-request-action@v1
      with:
         github-token: ${{ secrets.PAT }}
         number: ${{ env.PULL_REQUEST_NUMBER }}
    
    - name: Merge Pull request
      uses: juliangruber/merge-pull-request-action@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        number: ${{ env.PULL_REQUEST_NUMBER}}
        method: squash

    