name: DBT
on:
  push:
    branches:
      - local

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install dbt

    - name: Run DBT
      run: dbt run

    - name: Create pull request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: "DBT Update"
        body: "This pull request updates the DBT models."
        head: local
        base: main
