name: DBT Pull Request
on:
  push:
    branches:
      - nuevos_cambios

jobs:
   auto-pull-request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # - name: extract git commit data
    #   uses: rlespinasse/git-commit-data-action@v1.x
    
    # - name: Update author information
    #   run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: 
        pip install dbt-snowflake
    - name: Run DBT
      run: dbt run

    - name: Create Pull Request
      uses: vsoch/pull-request-action@master
      env:
         GITHUB_TOKEN: ${{ secrets.PAT }}
         BRANCH_PREFIX: ""
         PULL_REQUEST_BRANCH: "main"
         PULL_REQUEST_TITLE: "DBT Pull request"
         PULL_REQUEST_BODY: the body for the pull request

         
    - name: Check outputs
      run: |
        echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
       
    - name: Approve Pull Request
      uses: juliangruber/approve-pull-request-action@v1
      with:
         github-token: ${{ secrets.AUTHORIZATOR }}
         number: ${{ env.PULL_REQUEST_NUMBER }}
    
    - name: Merge Pull request
      uses: juliangruber/merge-pull-request-action@v1
      with:
         github-token: ${{ secrets.GITHUB_TOKEN }}
         number: ${{ env.PULL_REQUEST_NUMBER }}
         method: squash

    