name: DBT
on:
  push:
    branches:
      - local

permissions:
  pull-requests: write
  contents: write

jobs:
  Action-pull-request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: 
        pip install dbt-snowflake
    - name: Run DBT
      run: dbt run

    - name: Create pull request
      id: cpr
      uses: devops-infra/action-pull-request@v0.5.3
      with:
        github_token: ${{ secrets.PAT }}
        title: "DBT pull request "
        assignee: ${{ github.actor }}
        template: .github/PULL_REQUEST_TEMPLATE.md
        label: automatic,feature
        body: "This pull request updates the DBT models."
        source_branch: local
        target_branch: main
        allow_no_diff: false
           
    - name: Check outputs
      if: ${{ steps.cpr.outputs.pull-request-number }}
      run: |
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
               
    - name: Enable Pull Request Automerge
      if: steps.cpr.outputs.pull-request-operation == 'created'
      uses: peter-evans/enable-pull-request-automerge@v2
      with:
        token: ${{ secrets.PAT }}
        pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
        merge-method: squash