name: DBT
on:
  push:
    branches:
      - local

permissions:
  pull-requests: write
  contents: write

jobs:
  Action-pull-request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: 
        pip install dbt-snowflake
    - name: Run DBT
      run: dbt run

    - name: create-pull-request
      id: cpr
      uses: vsoch/pull-request-action@master
      env:
         GITHUB_TOKEN: ${{ secrets.PAT }}
         PULL_REQUEST_BRANCH: "main"
         PULL_REQUEST_TITLE: "DBT Pull request"
                
    - name: Check outputs
      env:
        pull_request_number_output: ${{ steps.cpr.outputs.pull_request_number }}
        pull_request_url_output: ${{ steps.cpr.outputs.pull_request_url }}
        pull_request_code_output: ${{ steps.cpr.outputs.pull_request_return_code }}
      run: |
        echo "Pull Request Number - ${pull_request_number_output}"
        echo "Pull Request URL - ${pull_request_url_output}"
        echo "Pull Request Code - ${pull_request_code_output}"
               
    - name: Enable Pull Request Automerge
      uses: peter-evans/enable-pull-request-automerge@v2
      with:
        token: ${{ secrets.PAT }}
        pull-request-number: ${PULL_REQUEST_NUMBER}
        merge-method: merge