name: DBT
on:
  push:
    branches:
      - local

permissions:
  pull-requests: write
  contents: write

jobs:
   auto-pull-request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # - name: Set up Python
    #   uses: actions/setup-python@v2
    #   with:
    #     python-version: 3.9

    # - name: Install dependencies
    #   run: 
    #     pip install dbt-snowflake
    # - name: Run DBT
    #   run: dbt run

    - name: pra
      uses: vsoch/pull-request-action@master
      env:
         GITHUB_TOKEN: ${{ secrets.PAT }}
         BRANCH_PREFIX: ""
         PULL_REQUEST_BRANCH: "main"
         PULL_REQUEST_TITLE: "DBT Pull request"
        
                
    - name: Check outputs
      run: |
        echo "Pull Request Number - ${{ steps.pra.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.pra.outputs.pull-request-url }}"
        echo "Pull Request Code - ${{ steps.pra.outputs.pull_request_return_code }}"
               
    - name: Enable Pull Request Automerge
      uses: peter-evans/enable-pull-request-automerge@v2
      with:
        token: ${{ secrets.PAT }}
        pull-request-number: ${{ steps.pra.outputs.pull_request_number }}
        merge-method: merge