name: DBT
on:
  push:
    branches:
      - local

permissions:
  pull-requests: write
  contents: write

jobs:
  Auto-Pull-Request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: 
        pip install dbt-snowflake
    - name: Run DBT
      run: dbt run

    - name: Create pull request
      id: cpr
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.PAT }}
        title: "DBT Update"
        body: "This pull request updates the DBT models."
        branch: local
        base: main
        
    - name: Auto approve
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: juliangruber/approve-pull-request-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.cpr.outputs.pull-request-number }}
